import React from 'react';
import classNames from 'classnames';

export interface AccessibilityDeclarationProps {
  /** All code generated by accessibility site */
  declaration: string;

  /** Css classes to declaration */
  classDeclaration?: string;
}

export const AccessibilityDeclaration = ({ declaration, classDeclaration }: AccessibilityDeclarationProps) => {
  const cssDeclaration = classNames('ama-accessibility-declaration', classDeclaration);
  return <div className={cssDeclaration} dangerouslySetInnerHTML={{ __html: declaration }}></div>;
};
